import argparse
import sys
import os

sys.path.append(os.path.join(os.path.dirname(__file__), "src"))

from roller_coaster.geometry import vec_mul, generate_demo_points
from roller_coaster.io import load_points_from_csv, format_scad
from roller_coaster.track import process_path_data, partition_path
from roller_coaster.render import render_segments


def main():
    parser = argparse.ArgumentParser(description="Generate OpenSCAD coaster data")
    parser.add_argument("file", nargs="?", help="CSV file with x,y,z coordinates")
    parser.add_argument(
        "--scale", type=float, default=1.0, help="Scale factor for points"
    )
    parser.add_argument(
        "--max-length", type=float, default=250.0, help="Max segment length (mm)"
    )
    parser.add_argument(
        "--render", action="store_true", help="Render to STL using OpenSCAD"
    )
    parser.add_argument(
        "--openscad", default="openscad", help="Path to OpenSCAD executable"
    )
    parser.add_argument(
        "--output-dir", default=".", help="Directory to save output STL files"
    )
    args = parser.parse_args()

    points = []
    if args.file:
        print(f"Reading points from {args.file}...")
        points = load_points_from_csv(args.file)
        if not points:
            print("No valid points found in CSV.")
            sys.exit(1)
    else:
        print("No file provided. Generating demo path...")
        points = generate_demo_points(steps=2000)

    if args.scale != 1.0:
        print(f"Scaling points by {args.scale}...")
        points = [vec_mul(p, args.scale) for p in points]

    print(f"Processing {len(points)} points...")
    path_data = process_path_data(points)

    print(f"Partitioning path (max length: {args.max_length}mm)...")
    segments, ranges, total_len = partition_path(path_data, args.max_length)
    print(f"Total Length: {total_len:.2f}mm. Created {len(segments)} segments.")

    scad_content, num_segments = format_scad(
        segments, ranges, total_len, crosstie_spacing=25
    )

    with open("spline_data.scad", "w") as f:
        f.write(f"// Generated by generate.py\n")
        f.write(scad_content)

    print(f"Done. Wrote data to spline_data.scad")

    if args.render:
        render_segments(num_segments, args.openscad, args.output_dir)


if __name__ == "__main__":
    main()
